services:
  - type: web
    name: rgfl-survivor
    env: node
    plan: free
    buildCommand: npm install && npm run build && npx prisma migrate deploy
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: rgfl-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 5050
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: rgfl-db
    plan: free
    databaseName: rgfl_db
    user: rgfl_user
